/**
 * Tokens Studio JSON → CSS Variables generator.
 * Reads tokens/{global,dark,light}.json and generates src/styles/tokens.css
 *
 * Usage: node scripts/build-tokens.mjs
 *
 * When Tokens Studio pushes updated JSON to Git, run this script
 * (or add it to CI) to regenerate CSS variables.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

function loadJSON(name) {
  return JSON.parse(readFileSync(resolve(root, 'tokens', name), 'utf-8'));
}

function flattenTokens(obj, prefix = '') {
  const result = [];
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}-${key}` : key;
    if (val && typeof val === 'object' && 'value' in val) {
      result.push({ name: path, value: val.value, type: val.type });
    } else if (val && typeof val === 'object') {
      result.push(...flattenTokens(val, path));
    }
  }
  return result;
}

function tokenToCSS(token) {
  const name = `--obs-${token.name}`;
  let value = token.value;

  // Add units for sizing tokens
  if (['fontSizes', 'spacing', 'borderRadius', 'borderWidth'].includes(token.type) && !String(value).includes('px')) {
    value = `${value}px`;
  }

  return `  ${name}: ${value};`;
}

// Load tokens
const global = loadJSON('global.json');
const dark = loadJSON('dark.json');
const light = loadJSON('light.json');

const globalTokens = flattenTokens(global);
const darkTokens = flattenTokens(dark);
const lightTokens = flattenTokens(light);

// Generate CSS
const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT */
/* Source: tokens/*.json (synced from Figma via Tokens Studio) */

:root {
  /* Global tokens */
${globalTokens.map(tokenToCSS).join('\n')}
}

:root,
.light,
[data-theme="light"] {
  /* Light theme */
${lightTokens.map(tokenToCSS).join('\n')}
}

.dark,
[data-theme="dark"] {
  /* Dark theme */
${darkTokens.map(tokenToCSS).join('\n')}
}
`;

const outPath = resolve(root, 'src', 'styles', 'tokens.css');
writeFileSync(outPath, css, 'utf-8');

console.log(`Generated ${outPath}`);
console.log(`  Global: ${globalTokens.length} tokens`);
console.log(`  Light:  ${lightTokens.length} tokens`);
console.log(`  Dark:   ${darkTokens.length} tokens`);
console.log(`  Total:  ${globalTokens.length + lightTokens.length + darkTokens.length} tokens`);
